export const stockProductos = [
  {
    id: 1,
    title: "Maia Blue",
    precio: 8900,
    stock: 3,
    descripcion: "Jean azul oscuro, tiro medio, elastizado. TALLES: 36 al 48",
    descripciondetalle: "Jean Azul Oscuro. TALLES: 36 al 48",
    categoria: "jeans",
    img: "https://res.cloudinary.com/dy66f9pgr/image/upload/v1681943734/React%20multimedia/maia_jean_blue_rczozu.jpg",
  },

  {
    id: 2,
    title: "Electra White",
    precio: 10200,
    stock: 10,
    descripcion: "Jean blanco, tiro alto, rigido, buen calce. TALLES: 36 al 50",
    descripciondetalle: "Jean Blanco. TALLES: 36 al 50",
    categoria: "jeans",
    img: "https://res.cloudinary.com/dy66f9pgr/image/upload/v1681943735/React%20multimedia/electra_jean_white_wnxnso.jpg",
  },

  {
    id: 3,
    title: "Alexa Blue",
    precio: 9800,
    stock: 10,
    descripcion:
      "Jean azul claro, tiro medio, rigido, buen calce. TALLES: 40 al 56",
    descripciondetalle: "Jean Azul Claro. TALLES: 40 al 56",
    categoria: "jeans",
    img: "https://res.cloudinary.com/dy66f9pgr/image/upload/v1681943734/React%20multimedia/alexa_jean_blue_brpjet.jpg",
  },

  {
    id: 4,
    title: "Rosemary Grey",
    precio: 12500,
    stock: 10,
    descripcion:
      "Jean gris claro, tiro alto, super elastizado. TALLES: 38 al 50",
    descripciondetalle: "Jean Gris Claro.TALLES: 38 al 50",
    categoria: "jeans",
    img: "https://res.cloudinary.com/dy66f9pgr/image/upload/v1681943736/React%20multimedia/rosemary_jean_grey_uppjwy.jpg",
  },

  {
    id: 5,
    title: "Cindy Light Blue",
    precio: 10300,
    stock: 10,
    descripcion:
      "Jean celeste, tiro alto, elastizado con roturas. TALLES: 42 al 56",
    descripciondetalle: "Jean Celeste. TALLES: 42 al 56",
    categoria: "jeans",
    img: "https://res.cloudinary.com/dy66f9pgr/image/upload/v1681943735/React%20multimedia/cindy_jean_lightblue_bsjyy5.jpg",
  },
  {
    id: 6,
    title: "Cleo Dark Blue",
    precio: 9200,
    stock: 10,
    descripcion:
      "Jean azul oscuro nevado, tiro alto, elastizado. TALLES: 38 al 48",
    descripciondetalle: "Jean Azul Oscuro.TALLES: 38 al 48",
    categoria: "jeans",
    img: "https://res.cloudinary.com/dy66f9pgr/image/upload/v1681943734/React%20multimedia/cleo_jean_bluedark_xbwson.jpg",
  },
  {
    id: 7,
    title: "Combo Britney",
    precio: 7800,
    stock: 20,
    descripcion:
      "Gorra negra y frase de Britney en borado blanco + remera estampada de Britney .",
    descripciondetalle:
      "Gorra + remera estampada de Britney. TALLES: S, M, L, XXL",
    categoria: "accesorios",
    img: "https://res.cloudinary.com/dy66f9pgr/image/upload/v1682450578/React%20multimedia/gorra_feriaimpro_negra_vrkiyo.jpg",
  },
  {
    id: 8,
    title: "Combo Style",
    precio: 6500,
    stock: 10,
    descripcion:
      "Piluso negro con argollas, tela gabardina + Lentes planos negros.",
    descripciondetalle: "Piluso Negro con argollas. TALLES: Unico",
    categoria: "accesorios",
    img: "https://res.cloudinary.com/dy66f9pgr/image/upload/v1682450578/React%20multimedia/anteojos_feriaimpro_varios_g59dnr.jpg",
  },
  {
    id: 9,
    title: "Bandolera Yellow",
    precio: 3200,
    stock: 10,
    descripcion: "Bandolera color Maiz con precinto ajustable",
    descripciondetalle: "Bandolera color Maiz. TALLES: Unico",
    categoria: "accesorios",
    img: "https://res.cloudinary.com/dy66f9pgr/image/upload/v1682450578/React%20multimedia/bandolera_feriaimpro_yellow_li7eyz.jpg",
  },
  {
    id: 10,
    title: "Campera Orange LP",
    precio: 13200,
    stock: 10,
    descripcion: "Campera corta de jean color naranja. Talles: S,M,L,XL",
    descripciondetalle: "Campera jean Naranja. TALLES: S,M,L,XL",
    categoria: "camperas",
    img: "https://res.cloudinary.com/dy66f9pgr/image/upload/v1682450552/React%20multimedia/campera_laslocas_orange_krcbmo.jpg",
  },
  {
    id: 11,
    title: "Campera Blue Las Locas",
    precio: 9900,
    stock: 10,
    descripcion: "Campera deportiva de algodon con cierre. Talles S,M,L,XL",
    descripciondetalle: "Campera deportiva con Cierre. TALLES: S,M,L,XL",
    categoria: "camperas",
    img: "https://res.cloudinary.com/dy66f9pgr/image/upload/v1682450552/React%20multimedia/campera_laslocas_blue_qhjlqf.jpg",
  },
  {
    id: 12,
    title: "Campera Puffer Las Locas",
    precio: 25500,
    stock: 10,
    descripcion: "Campera puffer opaca. Talles 1,2,3,4,5",
    descripciondetalle: "Campera Puffer. TALLES: 1,2,3,4,5",
    categoria: "camperas",
    img: "https://res.cloudinary.com/dy66f9pgr/image/upload/v1682450551/React%20multimedia/campera_laslocas_puffer_zl6ga0.jpg",
  },
  {
    id: 13,
    title: "Chaleco puffer Celeste Las Locas",
    precio: 20500,
    stock: 10,
    descripcion: "Chaleco puffer opaco celeste. Talles 1,2,3,4,5",
    descripciondetalle: "Chaleco Puffer Celeste. TALLES: 1,2,3,4,5",
    categoria: "camperas",
    img: "https://res.cloudinary.com/dy66f9pgr/image/upload/v1682450551/React%20multimedia/chaleco_laslocas_puffer_enttm9.jpg",
  },
];
